name: flutter_headset_detector
description: Flutter Plugin for headset events. Detect headset is plugged and unplugged. Get current headset state.
version: 2.1.1
author: songyiYu<songyi0207@gmail.com>, yenoss<cpg0504@gmail.com>, FlutterMoum Group<fluttermoum@gmail.com>, Blake Helms (helmsb), Rafael Delos Santos (themobilecoder), KuKu <turlvo@gmail.com>
homepage: https://github.com/turlvo/flutter_headset_detector

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.13

flutter:
  plugin:
    platforms:
      android:
        package: flutter.moum.flutter_headset_detector
        pluginClass: FlutterHeadsetDetectorPlugin
      ios:
        pluginClass: FlutterHeadsetDetectorPlugin
